// Bloque 1: Adjetivos (82)
const ADJETIVOS = [
"RAPIDO","LENTO","GRANDE","PEQUEÑO","FELIZ","TRISTE","BRILLANTE","OBSCURO",
"AMABLE","FUERTE","SUAVE","CLARO","DULCE","AGRIO","SALADO","FRIO","CALIENTE",
"ALTO","BAJO","ANCHO","ESTRECHO","LARGO","CORTO","LIGERO","PESADO","REDONDO","CUADRADO",
"FACIL","DIFICIL","RUIDOSO","SILENCIOSO","LUMINOSO","TENUE","FRAGIL","DEBIL","VIOLENTO",
"RUGOSO","LISO","ARRUGADO","AMARGO","SANO","ENFERMO","JOVEN","VIEJO","NUEVO","CONTUNDENTE",
"SUTIL","HONESTO","FALSO","VIVO","MUERTO","ROJO","AZUL","VERDE","AMARILLO","NEGRO",
"BLANCO","MORADO","NARANJA","GRIS","ROSA","CLASICO","MODERNO","ELEGANTE","FEO","BONITO",
"HERMOSO","IMPORTANTE","SENCILLO","COMPLEJO","SORPRENDENTE","ABURRIDO","DIVERTIDO",
"HUMANO","ANIMAL","VEGETAL","ARTIFICIAL","NATURAL","CERCANO","LEJANO","ÚTIL","INÚTIL"
];

// Bloque 2: Sustantivos comunes (73)
const SUSTANTIVOS = [
"CASA","PERRO","GATO","ARBOL","COCHE","LIBRO","CARTA","RATON","FLOR","AGUA","FUEGO",
"TIERRA","AIRE","MESA","SILLA","VENTANA","PUERTA","ESPEJO","CUADERNO","LAPIZ",
"TELEFONO","ORDENADOR","BOLSA","ZAPATO","SOMBRERO","RELOJ","CUCHILLO","TENEDOR","PLATO",
"VASO","SOPA","PAN","QUESO","MANZANA","NARANJA","BANANA","PERIODICO","REVISTA",
"BICICLETA","MOTOCICLETA","AUTOBUS","TREN","AVION","BARCO","JARDIN","HOSPITAL",
"COLEGIO","ESCUELA","PUERTO","PARQUE","MERCADO","TIENDA","IGLESIA","CINE","TEATRO",
"ESTADIO","PLAYA","MONTAÑA","RIO","LAGO","OCEANO","CIELO","SOL","LUNA","ESTRELLA","NUBE",
"LLUVIA","NIEVE","VIENTO","TORRE","PUENTE","CAMINO","BARRIO"
];

// Bloque 3: Verbos comunes (78)
const VERBOS = [
"CORRER","SALTAR","DORMIR","COMER","LEER","ESCRIBIR","PINTAR","BEBER","CAMINAR","HABLAR",
"ESCUCHAR","VER","OIR","JUGAR","CANTAR","BAILAR","TRABAJAR","ESTUDIAR","APRENDER","ENSEÑAR",
"CONDUCIR","VIAJAR","COMPRAR","VENDER","ABRIR","CERRAR","LAVAR","COCINAR","LLEGAR","SALIR",
"ENTRAR","SUBIR","BAJAR","DAR","RECIBIR","ESPERAR","CAMBIAR","PENSAR","SENTIR",
"CREAR","DESARROLLAR","PLANEAR","DECIDIR","PREFERIR","GUSTAR","AMAR","ODIAR","VIVIR","MORIR",
"ENCONTRAR","PERDER","GUARDAR","ROMPER","REPARAR","BUSCAR","SACAR","INTRODUCIR","CONSTRUIR","DESTRUIR",
"PROBAR","HUIR","SEGUIR","AYUDAR","OLVIDAR","RECORDAR","ACORDAR","PAGAR","COBRAR",
"APOYAR","ESFORZAR","REIR","LLORAR","TOMAR","LLEVAR","TRAER","DEJAR","AGARRAR","SOLTAR"
];

// Bloque 4: Ríos de España (40)
const RIOS = [
"EBRO","TAJO","DUERO","GUADALQUIVIR","JUCAR","SEGURA","GUADIANA","MIÑO","SIL","LLOBREGAT",
"BERMEJO","NERBIO","NALON","TIETAR","TIERRA","TORMES","ESLA","CARRION","SORIA","HUESCA",
"TERUEL","MADELA","MANZANARES","LOZOYA","RIACHUELA","TAIBILLA","BESOS","CACERES","ALAGON","GUEJAR",
"ALHAMA","TURIA","ORBIGO","CHICLANA","GUADIARO","RIUADA","FLUMEN","FRESNO","CONDE","BASO"
];

// Bloque 5: Comunidades, ciudades autónomas, provincias y ciudades de España (64)
const CIUDADES_PROVINCIAS = [
"ANDALUCIA","ARAGON","ASTURIAS","BALEARES","CANARIAS","CANTABRIA","CASTILLALEON","CASTILLALAMANCHA",
"CATALUÑA","EXTREMADURA","GALICIA","LARIOJA","MADRID","MURCIA","NAVARRA","PAISVASCO","VALENCIA",
"CEUTA","MELILLA",
"ALAVA","ALBACETE","ALMERIA","AVILA","BADAJOZ","BARCELONA","BURGOS","CACERES","CADIZ",
"CASTELLON","CIUDADREAL","CORDOBA","CORUÑA","CUENCA","GIPUZKOA","GERONA","GRANADA","GUADALAJARA",
"HUELVA","HUESCA","JAEN","LEON","LLEIDA","LUGO","MALAGA","OURENSE","PALENCIA","PONTEVEDRA",
"SALAMANCA","SANTACRUZ","SEGOVIA","SEVILLA","SORIA","TARRAGONA","TERUEL","TOLEDO","VALLADOLID",
"VIZCAYA","ZAMORA","ZARAGOZA",
"PALMA","LASPALMAS","VIGO","GIJON","EIBAR"
];

// Bloque 6: Países y capitales (69)
const PAISES_CAPITALES = [
"ESPAÑA","FRANCIA","ALEMANIA","ITALIA","PORTUGAL","INGLATERRA","IRLANDA","SUECIA","NORUEGA","FINLANDIA",
"RUSIA","CHINA","JAPON","COREA","INDIA","PAKISTAN","EGIPTO","MARRUECOS","ARGENTINA","BRASIL",
"MEXICO","COLOMBIA","CHILE","PERU","VENEZUELA","CUBA","CANADA","EEUU","AUSTRALIA","NUEVAZELANDA",
"BRUSELAS","PARIS","BERLIN","ROMA","LISBOA","LONDRES","DUBLIN","ESTOCOLMO","OSLO","HELSINKI",
"MOSCU","PEKIN","TOKIO","SEUL","DELHI","ISLAMABAD","ELCAIRO","RABAT","BUENOSAIRES","BRASILIA",
"WASHINGTON","OTTAWA","LIMA","SANTIAGO","CARACAS","AMSTERDAM","VIENA","PRAGA","BUDAPEST","ATENAS",
"COPENHAGUE","MONACO","DOHA","RIAD","KABUL","TEHERAN","ANKARA","DAMASCO","AMMAN"
];

// Bloque 7a: Montañas, ríos y lagos de España (19)
const GEOGRAFICOS_ESPANA = [
"ANETO","MULHACEN","TEIDE","MONCAYO","GUADARRAMA","PICOS","SIERRA","EBRO","TAJO","DUERO",
"GUADIANA","JUCAR","SEGURA","MIÑO","SIL","LLOBREGAT","ORBIGO","TURIA","NALON"
];

// Bloque 7b: Montañas, ríos y lagos del mundo (20)
const GEOGRAFICOS_MUNDO = [
"EVEREST","KILIMANJARO","ALPES","ANDES","HIMALAYA","CAUCASO","TITICACA","BAIKAL","VICTORIA","TAMESIS",
"NILO","AMAZONAS","MISSISSIPPI","GANGES","DANUBIO","RIN","LOIRE","MEKONG","YANGTZE","HUDSON"
];

// Bloque 8: Adverbios y expresiones comunes (29)
const ADVERBIOS = [
"SIEMPRE","NUNCA","AHORA","TARDE","TEMPRANO","LEJOS","CERCA","RAPIDO","LENTO","BIEN",
"MAL","ANTES","DESPUES","ADEMAS","TAMBIEN","SOLO","JUNTO","AQUI","ALLI",
"ADELANTE","ATRAS","ARRIBA","ABAJO","ENCIMA","DEBAJO","DETRAS","PRONTO","TANTO","MUCHO"
];

const WORD_BANK = ADJETIVOS
  .concat(SUSTANTIVOS)
  .concat(VERBOS)
  .concat(RIOS)
  .concat(CIUDADES_PROVINCIAS)
  .concat(PAISES_CAPITALES)
  .concat(GEOGRAFICOS_ESPANA)
  .concat(GEOGRAFICOS_MUNDO)
  .concat(ADVERBIOS);
